In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/MonthlySales.csv')

In [4]:
df

         month      sales
0   2013-01-01   14236.90
1   2013-02-01    4519.89
2   2013-03-01   55691.01
3   2013-04-01   28295.35
4   2013-05-01   23648.29
5   2013-06-01   34595.13
6   2013-07-01   33946.39
7   2013-08-01   27909.47
8   2013-09-01   81777.35
9   2013-10-01   31453.39
10  2013-11-01   78628.72
11  2013-12-01   69545.62
12  2014-01-01   18174.08
13  2014-02-01   11951.41
14  2014-03-01   38726.25
15  2014-04-01   34195.21
16  2014-05-01   30131.69
17  2014-06-01   24797.29
18  2014-07-01   28765.33
19  2014-08-01   36898.33
20  2014-09-01   64595.92
21  2014-10-01   31404.92
22  2014-11-01   75972.56
23  2014-12-01   74919.52
24  2015-01-01   18542.49
25  2015-02-01   22867.71
26  2015-03-01   51186.22
27  2015-04-01   39248.59
28  2015-05-01   56691.08
29  2015-06-01   39430.44
30  2015-07-01   38440.76
31  2015-08-01   33265.56
32  2015-09-01   72908.11
33  2015-10-01   56463.13
34  2015-11-01   82192.32
35  2015-12-01   97237.42
36  2016-01-01   44703.14
37  2016-02-01   20301.13
38  2016-03-01   58872.35
39  2016-04-01   36521.54
40  2016-05-01   44261.11
41  2016-06-01   52981.73
42  2016-07-01   45264.42
43  2016-08-01   63120.89
44  2016-09-01   87866.65
45  2016-10-01   77776.92
46  2016-11-01  118447.83
47  2016-12-01   83829.32

In [5]:
import json
from pandas.io.json import json_normalize

with open('data/monthlySalesbyCategoryMultiple.json') as json_data:
    d = json.load(json_data)

In [6]:
df = json_normalize(d['contents'], 'monthlySales', ['category', 'region'])

In [7]:
df

       month  sales    category region
0   20130101     38   Furniture   West
1   20130201     35   Furniture   West
2   20130301     41   Furniture   West
3   20130401     55   Furniture   West
4   20130501     58   Furniture   West
5   20130601     66   Furniture   West
6   20130701     74   Furniture   West
7   20130801     78   Furniture   West
8   20130901     38   Furniture   West
9   20131001     30   Furniture   West
10  20131101     26   Furniture   West
11  20131201     29   Furniture   West
12  20130101     54  Technology   West
13  20130201     66  Technology   West
14  20130301     77  Technology   West
15  20130401     70  Technology   West
16  20130501     60  Technology   West
17  20130601     63  Technology   West
18  20130701     55  Technology   West
19  20130801     47  Technology   West
20  20130901     55  Technology   West
21  20131001     30  Technology   West
22  20131101     22  Technology   West
23  20131201     77  Technology   West

In [8]:
#reading parquet into panda dataframe
import pyarrow.parquet as pq

In [9]:
table = pq.read_table('data/MonthlyProductSales.parquet')

In [10]:
table.to_pandas()

,Month of Order Date,Product Name,Sales
0,b'2017-01-13',b'Xerox 1972',11
1,b'2017-01-13',b'Xerox 1923',37
2,b'2017-01-13',b'Xerox 225',19
3,b'2017-01-13',b'Xerox 195',40
4,b'2017-01-13',b'Wireless Extenders zBoost YX545 SOHO Signal ...,756
5,b'2017-01-13',"b'Wirebound Service Call Books, 5 1/2"" x 4""'",19
6,b'2017-01-13',b'Wilson Jones 14 Line Acrylic Coated Pressboa...,11
7,b'2017-01-13',b'Ultra Door Push Plate',15
8,b'2017-01-13',b'Ultra Door Pull Handle',25
9,b'2017-01-13',"b'Tyvek Top-Opening Peel & Seel Envelopes, Pl...",109
10,b'2017-01-13',"b'TOPS Carbonless Receipt Book, Four 2-3/4 x 7...",56
11,b'2017-01-13',b'Tennsco 6- and 18-Compartment Lockers',1326
12,b'2017-01-13',b'Storex Dura Pro Binders',30
13,b'2017-01-13',b'Staple envelope',35
14,b'2017-01-13',b'Space Solutions HD Industrial Steel Shelving.',230
15,b'2017-01-13',b'Southworth 25% Cotton Granite Paper & Envelo...,7
16,b'2017-01-13',"b'Sauder Facets Collection Library, Sky Alder ...",291
17,b'2017-01-13',b'Sauder Cornerstone Collection Library',62
18,b'2017-01-13',"b'Safco Value Mate Series Steel Bookcases, Bak...",142
19,b'2017-01-13',"b'SAFCO Commercial Wire Shelving, 72h'",490
20,b'2017-01-13',b'SAFCO Boltless Steel Shelving',273
21,b'2017-01-13',b'Round Specialty Laser Printer Labels',30
22,b'2017-01-13',b'Rogers Handheld Barrel Pencil Sharpener',5
23,b'2017-01-13',"b'REDIFORM Incoming/Outgoing Call Register, 11...",17
24,b'2017-01-13',b'Recycled Steel Personal File for Hanging Fil...,57
25,b'2017-01-13',"b'Pressboard Covers with Storage Hooks, 9 1/2""...",4
26,b'2017-01-13',b'Plantronics S12 Corded Telephone Headset Sys...,647
27,b'2017-01-13',b'Panasonic KP-4ABK Battery-Operated Pencil Sh...,44
28,b'2017-01-13',"b""O'Sullivan Elevations Bookcase, Cherry Finish""",334
29,b'2017-01-13',"b""O'Sullivan 4-Shelf Bookcase in Odessa Pine""",181
...,...,...,...
9222,b'2017-12-16',b'Aluminum Screw Posts',37
9223,b'2017-12-16',b'Akro-Mils 12-Gallon Tote',30
9224,b'2017-12-16',b'Advantus Rolling Drawer Organizers',62
9225,b'2017-12-16',"b'Advantus Push Pins, Aluminum Head'",52
9226,b'2017-12-16',b'Advantus Panel Wall Acrylic Frame',9
9227,b'2017-12-16',b'Adtran 1202752G1',302
9228,b'2017-12-16',b'Adjustable Personal File Tote',33
9229,b'2017-12-16',b'Adjustable Depth Letter/Legal Cart',1270
9230,b'2017-12-16',b'Adams Telephone Message Book W/Dividers/Spac...,12
9231,b'2017-12-16',"b'Adams Phone Message Book, 200 Message Capaci...",28
9232,b'2017-12-16',b'Acrylic Self-Standing Desk Frames',9
9233,b'2017-12-16',b'Acme Office Executive Series Stainless Steel...,26
9234,b'2017-12-16',b'Acme Hot Forged Carbon Steel Scissors with N...,70
9235,b'2017-12-16',b'Accohide Poly Flexible Ring Binders',6
9236,b'2017-12-16',"b'Acco Recycled 2"" Capacity Laser Printer Hang...",13
9237,b'2017-12-16',"b'Acco Pressboard Covers with Storage Hooks, 1...",8
9238,b'2017-12-16',"b'Acco Pressboard Covers with Storage Hooks, 9...",15
9239,b'2017-12-16',b'Acco Glide Clips',20
9240,b'2017-12-16',b'Acco Four Pocket Poly Ring Binder with Label...,18
9241,b'2017-12-16',b'Acco Economy Flexible Poly Round Ring Binder',3
9242,b'2017-12-16',b'Acco Data Flex Cable Posts For Top & Bottom ...,33
9243,b'2017-12-16',"b'Acco Banker\'s Clasps, 5 3/4""-Long'",17
9244,b'2017-12-16',b'Acco 6 Outlet Guardian Premium Plus Surge Su...,29
9245,b'2017-12-16',b'Acco 3-Hole Punch',18
9246,b'2017-12-16',"b'#10- 4 1/8"" x 9 1/2"" Recycled Envelopes'",44
9247,b'2017-12-16',b'14-7/8 x 11 Blue Bar Computer Printout Paper',96
9248,b'2017-12-16',"b'6"" Cubicle Wall Clock, Black'",10
9249,b'2017-12-16',b'3M Hangers With Command Adhesive',10
9250,b'2017-12-16',b'3.6 Cubic Foot Counter Height Office Refrige...,295
9251,b'2017-12-16',b'3-ring staple pack',9

In [11]:
# you need to install html5lib
# pip install html5lib
# reading data from a html site
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations')

In [12]:
# get part that has the states and abbreviations
df_usa = df[0]

In [13]:
# remove unnecessary rows and columns
final_df = df_usa.drop(df_usa.index[range(0,11)]).drop(df_usa.columns[range(10,15)], axis=1)

In [14]:
# rename columns
final_df.rename(columns={0: 'Region Name', 1: 'Region Status', 2: 'ISO', 3: 'ANSI_Letter', 4: 'ANSI_Code'
                         , 5: 'USPS', 6: 'USCG', 7: 'GPO', 8: 'AP', 9: 'Other Abbreviations'}, inplace=True)

In [15]:
# reset index of rows
final_df.reset_index(drop=True)

,Region Name,Region Status,ISO,ANSI_Letter,ANSI_Code,USPS,USCG,GPO,AP,Other Abbreviations
0,United States of America,Federal state,US USA 840,US,00,NaN,NaN,U.S.,U.S.,U.S.A.
1,Alabama,State,US-AL,AL,01,AL,AL,Ala.,Ala.,NaN
2,Alaska,State,US-AK,AK,02,AK,AK,Alaska,Alaska,Alas.
3,Arizona,State,US-AZ,AZ,04,AZ,AZ,Ariz.,Ariz.,Az.
4,Arkansas,State,US-AR,AR,05,AR,AR,Ark.,Ark.,NaN
5,California,State,US-CA,CA,06,CA,CF,Calif.,Calif.,"Ca., Cal."
6,Colorado,State,US-CO,CO,08,CO,CL,Colo.,Colo.,Col.
7,Connecticut,State,US-CT,CT,09,CT,CT,Conn.,Conn.,Ct.
8,Delaware,State,US-DE,DE,10,DE,DL,Del.,Del.,De.
9,District of Columbia,Federal district,US-DC,DC,11,DC,DC,D.C.,D.C.,Wash. D.C.
10,Florida,State,US-FL,FL,12,FL,FL,Fla.,Fla.,"Fl., Flor."
11,Georgia,State,US-GA,GA,13,GA,GA,Ga.,Ga.,NaN
12,Hawaii,State,US-HI,HI,15,HI,HA,Hawaii,Hawaii,H.I.
13,Idaho,State,US-ID,ID,16,ID,ID,Idaho,Idaho,"Id., Ida."
14,Illinois,State,US-IL,IL,17,IL,IL,Ill.,Ill.,"Il., Ills., Ill's"
15,Indiana,State,US-IN,IN,18,IN,IN,Ind.,Ind.,In.
16,Iowa,State,US-IA,IA,19,IA,IA,Iowa,Iowa,"Ia., Ioa.[1]"
17,Kansas,State,US-KS,KS,20,KS,KA,Kans.,Kan.,"Ks., Ka."
18,Kentucky,State (Commonwealth),US-KY,KY,21,KY,KY,Ky.,Ky.,"Ken., Kent."
19,Louisiana,State,US-LA,LA,22,LA,LA,La.,La.,NaN
20,Maine,State,US-ME,ME,23,ME,ME,Maine,Maine,Me.
21,Maryland,State,US-MD,MD,24,MD,MD,Md.,Md.,NaN
22,Massachusetts,State (Commonwealth),US-MA,MA,25,MA,MS,Mass.,Mass.,NaN
23,Michigan,State,US-MI,MI,26,MI,MC,Mich.,Mich.,NaN
24,Minnesota,State,US-MN,MN,27,MN,MN,Minn.,Minn.,Mn.
25,Mississippi,State,US-MS,MS,28,MS,MI,Miss.,Miss.,NaN
26,Missouri,State,US-MO,MO,29,MO,MO,Mo.,Mo.,NaN
27,Montana,State,US-MT,MT,30,MT,MT,Mont.,Mont.,NaN
28,Nebraska,State,US-NE,NE,31,NE,NB,Nebr.,Neb.,NaN
29,Nevada,State,US-NV,NV,32,NV,NV,Nev.,Nev.,Nv.
...,...,...,...,...,...,...,...,...,...,...
48,Washington,State,US-WA,WA,53,WA,WN,Wash.,Wash.,"Wa., Wn.[2]"
49,West Virginia,State,US-WV,WV,54,WV,WV,W. Va.,W.Va.,"W.V., W. Virg."
50,Wisconsin,State,US-WI,WI,55,WI,WS,Wis.,Wis.,"Wi., Wisc."
51,Wyoming,State,US-WY,WY,56,WY,WY,Wyo.,Wyo.,Wy.
52,American Samoa,Insular area (Territory),AS ASM 016 US-AS,AS,60,AS,AS,A.S.,NaN,NaN
53,Guam,Insular area (Territory),GU GUM 316 US-GU,GU,66,GU,GU,Guam,NaN,NaN
54,Northern Mariana Islands,Insular area (Commonwealth),MP MNP 580 US-MP,MP,69,MP,CM,M.P.,NaN,NaN
55,Puerto Rico,Insular area (Territory),PR PRI 630 US-PR,PR,72,PR,PR,P.R.,NaN,NaN
56,U.S. Virgin Islands,Insular area (Territory),VI VIR 850 US-VI,VI,78,VI,VI,V.I.,NaN,U.S.V.I.
57,U.S. Minor Outlying Islands,Insular areas,UM UMI 581 US-UM,UM,74,NaN,NaN,NaN,NaN,NaN
58,Baker Island,island,UM-81,NaN,81,NaN,NaN,NaN,NaN,XB[3]
59,Howland Island,island,UM-84,NaN,84,NaN,NaN,NaN,NaN,XH[3]
60,Jarvis Island,island,UM-86,NaN,86,NaN,NaN,NaN,NaN,XQ[3]
61,Johnston Atoll,atoll,UM-67,NaN,67,NaN,NaN,NaN,NaN,XU[3]
62,Kingman Reef,atoll,UM-89,NaN,89,NaN,NaN,NaN,NaN,XM[3]
63,Midway Islands,atoll,UM-71,NaN,71,NaN,NaN,NaN,NaN,QM[3]
64,Navassa Island,island,UM-76,NaN,76,NaN,NaN,NaN,NaN,XV[3]
65,Palmyra Atoll[4],atoll[4],UM-95,NaN,95,NaN,NaN,NaN,NaN,XL[3]
66,Wake Island,atoll,UM-79,NaN,79,NaN,NaN,NaN,NaN,QW[3]
67,Micronesia,Freely associated state,FM FSM 583,FM,64,FM,NaN,NaN,NaN,NaN
68,Marshall Islands,Freely associated state,MH MHL 584,MH,68,MH,NaN,NaN,NaN,NaN
69,Palau,Freely associated state,PW PLW 585,PW,70,PW,NaN,NaN,NaN,NaN
70,U.S. Armed Forces – Americas[5],US military mail code,NaN,NaN,NaN,AA,NaN,NaN,NaN,NaN
71,U.S. Armed Forces – Europe[6],US military mail code,NaN,NaN,NaN,AE,NaN,NaN,NaN,NaN
72,U.S. Armed Forces – Pacific[7],US military mail code,NaN,NaN,NaN,AP,NaN,NaN,NaN,NaN
73,Northern Mariana Islands,Obsolete postal code[8],NaN,NaN,NaN,CM,NaN,NaN,NaN,NaN
74,Panama Canal Zone,Obsolete postal code,PZ PCZ 594,NaN,NaN,CZ,NaN,NaN,NaN,NaN
75,Nebraska,Obsolete postal code[9],NaN,NaN,NaN,NB,NaN,NaN,NaN,NaN
76,Philippine Islands,Obsolete postal code,PH PHL 608[10],NaN,NaN,PI,NaN,NaN,NaN,NaN
77,Trust Territory of the Pacific Islands,Obsolete postal code,PC PCI 582,NaN,NaN,TT,NaN,NaN,NaN,NaN